package project.finalproject1backend.exception.payment.iamport;

import project.finalproject1backend.exception.payment.IamportPaymentException;

public class IamportSingleIamportPaymentVerificationAmountException extends IamportPaymentException {
}
